spring.application.name=aquasolution
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=aquasolution_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=AquaSolution2026!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

logging.level.com.aquasolution=DEBUG

# Configuracion de correo Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aquagt.solution@gmail.com
spring.mail.password=idwf yuns xbsc niri
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# URL base del sistema
app.base-url=http://localhost:8080