spring.application.name=aquasolution
server.port=8080

# BASE DE DATOS AZURE SQL
spring.datasource.url=jdbc:sqlserver://aquasolution-server.database.windows.net:1433;database=aquasolution_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=aquasolution_admin
spring.datasource.password=@quaSOlution26
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

logging.level.com.aquasolution=INFO

# Configuracion de correo Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aquagt.solution@gmail.com
spring.mail.password=idwf yuns xbsc niri
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# URL base del sistema
app.base-url=http://aquasolution-aaggaqhyg2bjf0az.mexicocentral-01.azurewebsites.net

# Configuracion de subida de archivos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB
app.upload.dir=uploads/reportes